sayi = input("0 ile 3 arasında bir sayı giriniz: \:n")
if sayi== "0" : print("Sayınız 0")
elif sayi== "1" : print("Sayınız 1")
elif sayi== "2" : print("Sayınız 2")
elif sayi== "3" : print("Sayınız 3")
else : print("0 ile 3 arasında bir sayı girin!")